import { PublicLandingFaqItem } from "@/lib/public/types";

// answerHtml is already sanitized server-side (see renderMarkdownSafe) — the
// backend escapes any literal "<"/">" in the admin's Markdown source before
// parsing, so every tag here was generated by the Markdown renderer itself.
export function LandingFaq({ title, faq }: { title: string; faq: PublicLandingFaqItem[] }) {
  if (faq.length === 0) return null;

  return (
    <section className="border-b border-border">
      <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{title}</h2>
        </div>

        <div className="mt-8 flex flex-col divide-y divide-border rounded-xl border border-border bg-card">
          {faq.map((item) => (
            <details key={item.question} className="group px-5 py-4 open:pb-4">
              <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-medium text-foreground marker:content-none">
                {item.question}
                <span className="shrink-0 text-muted-foreground transition-transform group-open:rotate-45">+</span>
              </summary>
              <div
                className="mt-2 text-sm text-muted-foreground [&_a]:text-primary [&_a]:underline [&_li]:ml-4 [&_li]:list-disc [&_p+p]:mt-2"
                dangerouslySetInnerHTML={{ __html: item.answerHtml }}
              />
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}
